### ISSUE TITLE
Handle response body compression only in the gateway

### ISSUE THREAD

**Issue by groldan** [geoserver/geoserver-cloud#118]
Remove the gzip filter from the services, and let compression be handled by the gateway

e.g.:
```yaml
server:
  port: 8080
  instance-id: ${spring.application.name}:${spring.application.instance_id:${spring.cloud.client.ip-address}}:${server.port}
  compression:
    enabled: true
    mime-types:
    - application/xml
    - etc
```
