### ISSUE TITLE
Make OWS requests support lower case 'SERVICE' parameter

### ISSUE THREAD

**Issue by groldan** [geoserver/geoserver-cloud#15]
Web-ui builds lower case service URL's. (e.g. `http://localhost:9090/test/ows?service=WFS&...`)

The `Query` predicate used in the gateway-service's routes supports case insensitive query parameter values but not keys.

For example:
```
# WFS routes
      - id: wfs # proxies requests to gateway-service:/wfs to wfs-service:/wfs
        uri: lb://wfs-service #load balanced to the wfs-service instances
        predicates:
        - Path=/wfs,/{segment}/wfs,/schemas/wfs/**
      - id: wfs_ows
        uri: lb://wfs-service
        predicates:
        - Path=/ows,/{segment}/ows
        - Query=SERVICE, (?i:WFS)
```
