### ISSUE TITLE
Make wfs/wms enabled output formats configurable

### ISSUE THREAD

**Issue by groldan** [geoserver/geoserver-cloud#49]
Don't quite remember off the top of my head how that's done in vanilla GeoServer, so throwing this up as an idea here. Just as the enabled web components are configurable through `webui-service`'s config properties, the enabled output formats should be.

**Comment by groldan** [comment]
I mean something like this: https://github.com/camptocamp/geoserver-microservices/blob/11ed77dc/config/web-ui.yml#L26

```yaml
  web-ui:
    # Theese are all default values, here just for reference. You can omit them and add only the ones to disable or further configure
    security.enabled: true
    wfs.enabled: true
    wms.enabled: true
    wcs.enabled: true
    wps.enabled: true
    gwc.enabled: false # not ready yet
    demos:
      enabled: true
      wps-request-builder: true
      wcs-request-builder: true
      demo-requests: true
      srs-list: true
      reprojection-console: true
      layer-preview-page:
        enabled: true
        common-formats:
          open-layers: true
          gml: true
          kml: true
    tools:
      enabled: true
      resource-browser: true
      catalog-bulk-load: true
```
